import { defineMaterial } from '../../engine/types';
import { brickGenerator } from '../../generators/brick';

export default defineMaterial({
  id: 'brick-old-flemish',
  name: 'Old brick, Flemish bond',
  category: 'Masonry',
  description: 'Hand-made 19th-century bricks in Flemish bond with burnt headers, eroded lime mortar, soot and salt bloom.',
  generator: brickGenerator,
  seed: 8,
  params: {
    bond: 2,
    brickLength: 225,
    brickHeight: 70,
    mortar: 12,
    bricksPerRow: 3,
    courses: 14,
    cornerRadius: 5,
    edgeRound: 7,
    edgeWear: 5,
    chips: 0.65,
    chipDepth: 6,
    bulge: 1.2,
    tilt: 1.6,
    sandRelief: 0.6,
    pits: 0.6,
    colorA: '#7f4636',
    colorB: '#9c6049',
    colorC: '#633b32',
    colorVar: 1.2,
    darkBricks: 0.12,
    darkColor: '#3a2927',
    headerDark: 0.75,
    flashing: 0.6,
    mottle: 0.2,
    speckle: 0.5,
    sandFacing: 0.5,
    mortarColor: '#bdb3a2',
    mortarDepth: 4,
    mortarProfile: 2,
    mortarGrain: 0.9,
    soot: 0.45,
    efflorescence: 0.3,
    streaks: 0.35,
    aoRadius: 30,
  },
});
