import { defineMaterial } from '../../engine/types';
import { brickGenerator } from '../../generators/brick';

/** Natural slate roof: overlapping courses (the brick generator's wedge makes the lower edges stand proud). */
export default defineMaterial({
  id: 'roof-slate',
  name: 'Slate roof',
  category: 'Stone',
  description: 'Blue-grey natural slates in broken bond with shadowed butt edges, a little lichen and runoff staining.',
  generator: brickGenerator,
  seed: 5,
  params: {
    bond: 0,
    brickLength: 300,
    brickHeight: 170,
    mortar: 4,
    bricksPerRow: 4,
    courses: 8,
    cornerRadius: 1.5,
    edgeRound: 1,
    edgeWear: 3.5,
    chips: 0.3,
    chipDepth: 2,
    bulge: 0,
    tilt: 1.2,
    wedge: 5,
    sandRelief: 0.2,
    pits: 0.1,
    colorA: '#4b5158',
    colorB: '#3f444b',
    colorC: '#585b5f',
    colorVar: 0.8,
    darkBricks: 0.1,
    darkColor: '#2b2e33',
    flashing: 0.15,
    mottle: 0.1,
    speckle: 0.1,
    sandColor: '#8a8a84',
    sandFacing: 0.05,
    brickRoughness: 0.7,
    mortarColor: '#1e2023',
    mortarDepth: 5,
    mortarProfile: 0,
    mortarGrain: 0.2,
    soot: 0.25,
    efflorescence: 0.08,
    streaks: 0.45,
    aoRadius: 30,
  },
});
