import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'barnwood-weathered',
  name: 'Weathered barn wood',
  category: 'Wood',
  description: 'Sun-bleached, rain-eroded softwood siding: silver-grey, raised latewood, checks, rusty nails, saw marks.',
  generator: woodGenerator,
  seed: 9,
  params: {
    boardWidth: 0.2,
    rows: 6,
    tileLength: 2.4,
    minPerRow: 1,
    maxPerRow: 2,
    gap: 5,
    gapDepth: 12,
    gapColor: '#120e0b',
    gapRoughness: 1,
    bevel: 1.5,
    heightVar: 1.2,
    cupping: 0.8,
    quarterSawn: 0.1,
    riftSawn: 0.25,
    pithMin: 0.05,
    pithMax: 0.2,
    cathedral: 1.2,
    ringWidth: 5,
    ringVar: 0.6,
    lateMin: 0.2,
    lateMax: 0.4,
    lateSharp: 0.85,
    ringWave: 2,
    poreType: 0,
    rays: 0.1,
    fiberContrast: 0.08,
    fiberScale: 0.8,
    fiberRelief: 0.06,
    latewoodRelief: 0.2,
    knotDensity: 1.8,
    knotSize: 14,
    deadKnots: 0.7,
    earlyColor: '#b89468',
    lateColor: '#8a6038',
    sapColor: '#c2a379',
    knotColor: '#4a3322',
    sapwood: 0.3,
    boardVariation: 1.4,
    roughness: 0.85,
    latewoodGloss: 0,
    wear: 0,
    weathering: 0.92,
    greyColor: '#8d877d',
    erosion: 1.4,
    checks: 0.7,
    nails: true,
    sawMarks: 0.5,
    aoStrength: 1.4,
  },
});
