import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'maple-curly',
  name: 'Curly maple',
  category: 'Wood',
  description: 'Figured hard maple with tiger-stripe curl that flips light/dark with the light direction, gloss lacquer.',
  generator: woodGenerator,
  seed: 21,
  params: {
    boardWidth: 0.2,
    rows: 4,
    tileLength: 1.6,
    minPerRow: 1,
    maxPerRow: 1,
    gap: 0.05,
    gapDepth: 0.1,
    gapColor: '#8a7255',
    bevel: 0,
    heightVar: 0,
    cupping: 0,
    quarterSawn: 0.35,
    riftSawn: 0.4,
    pithMin: 0.12,
    pithMax: 0.3,
    cathedral: 0.6,
    ringWidth: 2.2,
    ringVar: 0.4,
    lateMin: 0.12,
    lateMax: 0.25,
    lateSharp: 0.35,
    ringWave: 0.5,
    poreType: 2,
    poreSize: 0.035,
    poreDensity: 0.4,
    poreDepth: 0.01,
    poreDarkness: 0.15,
    rays: 0.5,
    raySize: 2.5,
    rayWidth: 0.1,
    rayTone: 0.14,
    fiberContrast: 0.03,
    knotDensity: 0,
    curl: 0.85,
    curlSpacing: 10,
    curlDepth: 0.16,
    curlTone: 0.1,
    earlyColor: '#ecdcbd',
    lateColor: '#dfc8a0',
    sapColor: '#ecdcbc',
    sapwood: 0,
    boardVariation: 0.6,
    blotch: 0.1,
    streaks: 0.15,
    roughness: 0.14,
    poreRoughness: 0.05,
    latewoodGloss: 0,
    wear: 0,
    clearcoat: 1,
    clearcoatRoughness: 0.04,
  },
});
