import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'oak-floorboards',
  name: 'White oak floorboards',
  category: 'Wood',
  description: 'Flat- and rift-sawn white oak planks, ring-porous with fine rays, satin lacquer, micro-bevel.',
  generator: woodGenerator,
  seed: 7,
  params: {
    rayLength: 20,
    boardWidth: 0.15,
    rows: 8,
    tileLength: 2.4,
    minPerRow: 1,
    maxPerRow: 2,
    gap: 0.4,
    bevel: 0.8,
    ringWidth: 2.6,
    lateMin: 0.6,
    lateMax: 0.8,
    lateSharp: 0.6,
    ringVar: 0.5,
    poreType: 1,
    poreSize: 0.13,
    poreDensity: 0.85,
    rays: 0.55,
    raySize: 14,
    rayWidth: 0.32,
    rayTone: 0.35,
    fiberContrast: 0.045,
    knotDensity: 0.25,
    knotSize: 7,
    earlyColor: '#9a7650',
    lateColor: '#c29e72',
    sapColor: '#d8c6a4',
    knotColor: '#5e3d22',
    roughness: 0.32,
  },
});
