import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'oak-herringbone-smoked',
  name: 'Smoked oak herringbone',
  category: 'Wood',
  description: 'Fumed oak parquet in a 45° herringbone, matte hard-wax oil, micro-bevelled blocks.',
  generator: woodGenerator,
  seed: 4,
  params: {
    rayLength: 20,
    pattern: 1,
    boardWidth: 0.09,
    herringboneRatio: 6,
    herringboneRepeats: 1,
    gap: 0.5,
    gapDepth: 2,
    gapColor: '#1a120c',
    bevel: 0.8,
    heightVar: 0.12,
    cupping: 0.05,
    quarterSawn: 0.15,
    riftSawn: 0.3,
    pithMin: 0.1,
    pithMax: 0.3,
    cathedral: 1.2,
    ringWidth: 2.4,
    ringVar: 0.5,
    lateMin: 0.6,
    lateMax: 0.8,
    lateSharp: 0.6,
    poreType: 1,
    poreSize: 0.13,
    poreDensity: 0.85,
    poreDarkness: 0.45,
    rays: 0.55,
    raySize: 14,
    rayWidth: 0.32,
    rayTone: 0.3,
    fiberContrast: 0.045,
    knotDensity: 0.6,
    knotSize: 5,
    earlyColor: '#43352a',
    lateColor: '#665142',
    sapColor: '#8f7c68',
    knotColor: '#24170e',
    sapwood: 0.08,
    boardVariation: 1.3,
    roughness: 0.55,
    poreRoughness: 0.12,
    wear: 0.35,
  },
});
