import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'oak-quartersawn',
  name: 'Quarter-sawn oak',
  category: 'Wood',
  description: 'Quarter-sawn white oak with pronounced ray fleck ("tiger rays"), straight grain, furniture lacquer.',
  generator: woodGenerator,
  seed: 5,
  params: {
    rayLength: 40,
    boardWidth: 0.15,
    rows: 8,
    tileLength: 2.4,
    minPerRow: 1,
    maxPerRow: 1,
    gap: 0.05,
    gapDepth: 0.2,
    bevel: 0,
    heightVar: 0.02,
    cupping: 0,
    quarterSawn: 0.85,
    riftSawn: 0.15,
    pithMin: 0.12,
    pithMax: 0.3,
    cathedral: 0.3,
    ringWidth: 2.4,
    ringVar: 0.5,
    lateMin: 0.6,
    lateMax: 0.8,
    lateSharp: 0.6,
    ringWave: 0.6,
    poreType: 1,
    poreSize: 0.13,
    poreDensity: 0.85,
    rays: 0.7,
    raySize: 12,
    rayWidth: 1.4,
    rayTone: 0.22,
    rayGloss: 0.14,
    fiberContrast: 0.035,
    knotDensity: 0,
    earlyColor: '#8c6f50',
    lateColor: '#ad9071',
    sapColor: '#d2bd98',
    sapwood: 0.05,
    roughness: 0.3,
    poreRoughness: 0.15,
    wear: 0.05,
  },
});
