import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'pine-knotty',
  name: 'Knotty pine paneling',
  category: 'Wood',
  description: 'Scots pine tongue-and-groove boards: sharp orange latewood, live and dead knots, V-groove joints.',
  generator: woodGenerator,
  seed: 11,
  params: {
    boardWidth: 0.12,
    rows: 10,
    tileLength: 2.4,
    minPerRow: 1,
    maxPerRow: 2,
    gap: 1.2,
    gapDepth: 4,
    gapColor: '#3a2615',
    bevel: 2.2,
    heightVar: 0.1,
    cupping: 0.15,
    quarterSawn: 0.05,
    riftSawn: 0.2,
    pithMin: 0.05,
    pithMax: 0.18,
    cathedral: 1.1,
    ringWidth: 4.2,
    ringVar: 0.55,
    lateMin: 0.18,
    lateMax: 0.38,
    lateSharp: 0.85,
    ringWave: 1.6,
    poreType: 0,
    rays: 0.15,
    raySize: 3,
    rayWidth: 0.05,
    rayTone: 0.05,
    fiberContrast: 0.035,
    fiberScale: 0.6,
    latewoodRelief: 0.02,
    knotDensity: 5,
    knotSize: 15,
    deadKnots: 0.3,
    earlyColor: '#ecd3a4',
    lateColor: '#c38c52',
    sapColor: '#ecd6ab',
    knotColor: '#6a3b1b',
    sapwood: 0.2,
    boardVariation: 1.1,
    blotch: 0.12,
    streaks: 0,
    roughness: 0.45,
    poreRoughness: 0,
    latewoodGloss: 0.06,
    wear: 0.05,
  },
});
