import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'teak-deck',
  name: 'Teak deck',
  category: 'Wood',
  description: 'Narrow teak deck planks with black rubber caulking, lightly weathered and unfinished.',
  generator: woodGenerator,
  seed: 14,
  params: {
    boardWidth: 0.06,
    rows: 20,
    tileLength: 2.4,
    minPerRow: 1,
    maxPerRow: 2,
    gap: 5,
    gapDepth: 0.6,
    gapColor: '#141414',
    gapRoughness: 0.55,
    bevel: 0.6,
    heightVar: 0.1,
    cupping: 0.1,
    quarterSawn: 0.5,
    riftSawn: 0.3,
    pithMin: 0.08,
    pithMax: 0.3,
    cathedral: 0.9,
    ringWidth: 3.5,
    ringVar: 0.5,
    lateMin: 0.3,
    lateMax: 0.55,
    lateSharp: 0.3,
    ringWave: 1.2,
    poreType: 2,
    poreSize: 0.1,
    poreDensity: 0.45,
    poreDepth: 0.06,
    poreDarkness: 0.35,
    rays: 0.3,
    raySize: 4,
    rayWidth: 0.1,
    fiberContrast: 0.09,
    fiberRelief: 0.02,
    latewoodRelief: 0.05,
    knotDensity: 0,
    earlyColor: '#a9773f',
    lateColor: '#8a5a2e',
    sapColor: '#c8a878',
    sapwood: 0.03,
    boardVariation: 1.3,
    blotch: 0.2,
    streaks: 0.5,
    roughness: 0.68,
    poreRoughness: 0.08,
    wear: 0.2,
    weathering: 0.3,
    greyColor: '#a39a8a',
    erosion: 0.3,
  },
});
