import { defineMaterial } from '../../engine/types';
import { woodGenerator } from '../../generators/wood';

export default defineMaterial({
  id: 'walnut-panel',
  name: 'Black walnut panel',
  category: 'Wood',
  description: 'Edge-glued American black walnut, flat-sawn cathedrals with occasional pale sapwood, oiled satin.',
  generator: woodGenerator,
  seed: 3,
  params: {
    boardWidth: 0.2,
    rows: 6,
    tileLength: 2.4,
    minPerRow: 1,
    maxPerRow: 1,
    gap: 0.05,
    gapDepth: 0.2,
    gapColor: '#241810',
    bevel: 0,
    heightVar: 0.02,
    cupping: 0,
    quarterSawn: 0.05,
    riftSawn: 0.15,
    pithMin: 0.1,
    pithMax: 0.28,
    cathedral: 1.3,
    ringWidth: 3.2,
    ringVar: 0.6,
    lateMin: 0.35,
    lateMax: 0.6,
    lateSharp: 0.15,
    ringWave: 1.0,
    poreType: 2,
    poreSize: 0.09,
    poreDensity: 0.55,
    poreDepth: 0.05,
    poreDarkness: 0.4,
    rays: 0.35,
    raySize: 5,
    rayWidth: 0.1,
    rayTone: 0.15,
    fiberContrast: 0.05,
    knotDensity: 0.15,
    knotSize: 6,
    deadKnots: 0.2,
    earlyColor: '#634836',
    lateColor: '#4b3629',
    sapColor: '#d2bb94',
    knotColor: '#2e1d13',
    sapwood: 0.12,
    boardVariation: 1.2,
    blotch: 0.18,
    streaks: 0.4,
    roughness: 0.46,
    poreRoughness: 0.12,
    wear: 0.1,
  },
});
